### ISSUE TITLE
Using state = 'DECLINED' param with q param ignores state

### ISSUE THREAD

**Issue by mgs96** [MunifTanjim/node-bitbucket#16]
Hello! I noticed that there's a bug when using the state param with q param, for example:

```
bitbucket.repositories.list({ page: 1, repo_slug: 'repository', state: 'DECLINED', q: 'created_on >=' + initialDate + ' AND created_on <=' + finalDate});
```
This will bring all pull requests between the dates requested regardless their state, however if the state is included in the query like this:
```
bitbucket.repositories.list({ page: 1, repo_slug: 'repository', q: 'created_on >=' + initialDate + ' AND created_on <=' + finalDate + ' AND state = "DECLINED"'});
```
then it works as expected.

**Comment by MunifTanjim** [comment]
Why do you think `repositories.list` will "bring all pull requests"?  This method is for listing repositories.

As for `pullrequests.list`, I can't do anything about how Bitbucket API handles the requests. All this library does is make requests according to the [official docs](https://developer.atlassian.com/bitbucket/api/2/reference/).

If you notice any bug in the API implementation, you'll have to report it to Bitbucket. As far as I know, https://bitbucket.org/site/master/issues - that is the place to do so.

If you think, this issue is actually caused by this library, feel free to comment, Otherwise, I'll go ahead and close the issue.

**Comment by mgs96** [comment]
I apologize, it was my mistake, the method was `bitbucket.repositories.listPullRequests` however I understand that the library is implemented as per bitbucket specification

**Comment by mgs96** [comment]
yeah, I'll close it
