### ISSUE TITLE
unhandled exception occurs on fetch call

### ISSUE THREAD

**Issue by ejlax** [MunifTanjim/node-bitbucket#19]
Attempting to create variables in repositories can throw an unhandled exception error which cannot be properly caught if the user does not have proper permissions.

``` UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:91125) UnhandledPromiseRejectionWarning: HTTPError: Your credentials lack one or more required privilege scopes.
    at getData.then.error (~/cli/node_modules/bitbucket/src/request/fetch.js:53:17)
```

 Unfortunately due to this my try / catch around this part of my code never gets called.

/bitbucket/src/request/fetch.js:53:17

**Comment by MunifTanjim** [comment]
That is an error returned from the Bitbucket's API server with status code `>= 400`.

What did you expect?

**Comment by ejlax** [comment]
@MunifTanjim Correct this is a correct error. However, it shouldn't be throwing an UNhandledPromiseRejectionWarning if it were being "handled" correctly. perhaps i am just doing this wrong, 

Here is the example i am working with:

```
      try {
        let {data,headers} = await bitbucket.pipelines.updateVariable({_body: updateVariable, repo_slug, username, variable_uuid})
      } catch (err) {
        cli.error(err)
      }
```
The catch never happens therefore my code continues and the variables are not properly set. Is there a way to catch the HTTPError in an instance like this so i can raise the Error and gracefully exit?

**Comment by MunifTanjim** [comment]
I couldn't reproduce the `UnhandledPromiseRejectionWarning`.

If you are wrapping your code with `try/catch` block (like your example code), there shouldn't be any `UnhandledPromiseRejectionWarning`.

> Is there a way to catch the HTTPError in an instance like this so i can raise the Error and gracefully exit?

If you want to know exactly that it is a `HTTPError` you can technically do this:

```js
const HTTPError = require('./src/request/http-error.js')

try {
  ...
} catch (err) {
  if (err instanceof HTTPError) {
    ...
  }
}
```

But it is not recommended, because this can change in the future. Don't treat it as a special case, treat it like any other errors.

I don't see any code for exiting the process. If you want to exit the process on catching error, you'll have to do that yourself.

That's all I can say from the given code example. Hope that helps...

**Comment by ejlax** [comment]
Thank you for your feedback. While i was never able to get this to work appropriately i am just working around it in another manner. I appreciate your time and thanks again for your work on this library.

**Comment by ejlax** [comment]
So i was able to get this error to properly catch. I was too deep in the code and in my top level i had missed the `await` so it was processing all of this code block asynchronously. Thanks for the help
