### ISSUE TITLE
source.get no longer a function..

### ISSUE THREAD

**Issue by rlyle** [MunifTanjim/node-bitbucket#22]
Whatever was in this last update broke us, we are now getting a bitbucket.source.get is not a function error when we try to run.. we had to force our package.json to 1.8.1 to fix our end..

**Comment by rlyle** [comment]
followup... I think you renamed get to read based on the commits I'm seeing. I think the proper thing to do when making breaking changes, is to do a major revision number version update instead of a minor revision.. this is certainly a breaking change.

**Comment by MunifTanjim** [comment]
@rlyle Really sorry about that. The last update had a lot of renames in it.

You can see the complete list here: https://github.com/MunifTanjim/node-bitbucket/issues/21#issuecomment-470604220

Bitbucket's API documentation has a lot of vague or wrong information in it. Because of that many method names in this library were totally wrong or not clear about what they do. That's why I tried to fix some of them in v`1.10.0`

I know this is a breaking change, but I wanted to make sure all the method names describes clearly about what they do before jumping to v`2.0.0`

The general rule I try to follow for naming the methods is:

- `list*` will return paginated list of objects
- `get*` will return single object

The exception to this rule is for the endpoint `/repositories/{username}/{repo_slug}/src/{node}/{path}`, which can return paginated list/metadata/file content based on the `path` parameter. That's why I renamed it to `read`.

Is it acceptable if I don't jump to v`2` at this moment (as I mentioned, I want to name all the endpoints correctly before doing that)?

**Comment by rlyle** [comment]
Well, just speaking from a point of view of maintaining libs, it might have been better to keep those changes in a branch until they were ready for release.. anyway, we forced our code to use version 1.8.1 and we're working again, so we do have a work-around.

**Comment by MunifTanjim** [comment]
> it might have been better to keep those changes in a branch until they were ready for release

I'll keep that in mind.
