### ISSUE TITLE
/list only works for the owner

### ISSUE THREAD

**Issue by yuliabaron** [MunifTanjim/node-bitbucket#28]
api.repositories.list() takes username as a MUST parameter and thus only returns repositories that are owned by this username regardless of the role specified, thus making impossible to get repos for the {role: 'contributor'}
For the official bitbucket API {username} is not a mandatory parameter, and thus when not provided results are filtered for the authenticated user and the {role} provided.

Could you fix this please?

**Comment by MunifTanjim** [comment]
> For the official bitbucket API {username} is not a mandatory parameter

This is not actually correct,

The endpoint for `repositories.list` is `/repositories/{username}`: [Offical docs](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D)

You can see why `username` is a mandatory parameter, because it's part of the endpoint url.

> only returns repositories that are owned by this username

You are probably expecting the `/repositories` endpoint: [Offical docs](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories)

In that case use [`repositories.listPublic`](https://bitbucketjs.netlify.com/#api-repositories-repositories_listPublic)

Hope that helps...

**Comment by yuliabaron** [comment]
This is the reply I've got from their support on this:

>Please be informed that the "authenticated user" and the "Username", are two separate things. The authenticated user is the user that you are checking for. The "Username" in the API will be referring to the repositories that is owned by the "Username"
>
>The reason I ask is because, with an authenticated call to `api.bitbucket.org/2.0/repositories?role=contributor` it would display the repositories that the authenticated user has "WRITE" access to.
>
>However, the moment you specify the username in the API request `api.bitbucket.org/2.0/repositories/<username>?role=contributor`, the API call will show results that the "authenticated user" has "WRITE" access to the repositories owned by the "Username" account. This is by design of the API.
>
>If the authenticated user (username) is the same as the username specified in the URL, then it would result in showing all repositories that the user has "WRITE" access to which includes the repositories that the user is owner of. This is because, the (authenticated user) is checking against repos on the same account. It shows the repo's that it owns is because the authenticated user does have write access to the repos.

**Comment by MunifTanjim** [comment]
From [v1.13.0](https://www.npmjs.com/package/bitbucket/v/1.13.0), you can do this:

```js
bitbucket.repositories.listPublic({
  role: 'contributor'
})
```

This will send the request to `/repositories?role=contributor`.

As for the name of *`/repositories`* endpoint `repositories.listPublic` should probably change (something like `repositories.listAccessible`?). If you have any suggestion for that, let me know. The endpoint name changes will be published on `v2` (whenever that happens).

**Comment by yuliabaron** [comment]
Great, thank you! 
Yes, I agree that `listAccessible` is a better name probably, but then it kinda overlaps `list`. Frankly, I would really prefer a single `list` endpoint. But that's up to you :)

Thanks again

**Comment by yuliabaron** [comment]
Btw, on the same subject. In this scenario I would expect that teams.list({ role: 'contributor' }) would return the team with the repo I have the `write` access to. For some reason this is not the case

**Comment by MunifTanjim** [comment]
>  I agree that listAccessible is a better name probably, but then it kinda overlaps list. Frankly, I would really prefer a single list endpoint. But that's up to you :)

The endpoints are automatically generated from the [API Specification](https://api.bitbucket.org/swagger.json) provided by Bitbucket. So, it's not actually my choice. Each entries in that specification is just given a name in this library. If I start to combine multiple entries from that specification together, it will quickly become messy because there are so many endpoints and new endpoints are added from time to time.

All we can do is give better name to those endpoints so that the name accurately reflects what the endpoints do. But since the official docs (which is also generated from the specification) is very inconsistent, sometimes it's hard to know what the endpoints actually do without working with it for some time first.

> Btw, on the same subject. In this scenario I would expect that teams.list({ role: 'contributor' }) would return the team with the repo I have the write access to. For some reason this is not the case

Because this library just uses the API Specification provided by Bitbucket, the general expectation is:

- If something's on the official docs, it'll be in this library.
- If something's wrong or missing from the official docs, it'll be the same in this library. (Unless someone points it out. In that case it is patched in the library. e.g. this issue)

So, `teams.list` is just a name for the `/teams` endpoint ([official docs](https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams), [library docs](https://bitbucketjs.netlify.com/#api-teams-teams_list)). If you think there is something wrong or missing in the official docs please open an issue with your findings.

**DEBUGGING TIPS**: If you run your app/script with the environment variable `DEBUG` set to `bitbucket` (i.e. `DEBUG=bitbucket`), you can see useful information about the api request in your console.

**Comment by yuliabaron** [comment]
Hi again,
I've tried the `listPublic` and no, it's not what I meant. This one indeed returns the list of all public repos, in fact an equivalent of `http://api.bitbucket.org/2.0/repositories`

While when making a call like this
curl -v -X GET \
   -H 'Authorization: Basic ****'  \
   -H 'Content-Type: application/json' \
   'https://api.bitbucket.org/2.0/repositories/?role=contributor'

Brings you only the list of repos you (as an authenticated user) were explicitly added as a contributor to. And this is also per the explanation given by the bitbucket.org support (quoted above)

**Comment by MunifTanjim** [comment]
I'm confused. What's the problem now? 😕

Could you please explain what you are expecting and what results are you getting with relevant code samples? 🤔

**Comment by yuliabaron** [comment]
I'm sorry I'm not clear.
Suppose you have a repo A. You're a full owner of A. You add user Test as a contributor of A. And supposer user Test only contributes to your repo.

I'm writing code that validates access to repos. I aim to show a user the list of repos he/she has an access to. 

For this I use `node-bitbucket` API in the following manner:
await this.api.repositories.list({
        username: 'Test',
        role: 'contributor',
        page,
        pagelen: 100,
      });

But this API returns me the empty list. 

If I use this API
await this.api.repositories.listPublic({
        role: 'contributor',
        page,
        pagelen: 100,
      });

It will return me the list of all public repos, which is a few good hundreds long list.

BUT if I ask Bitbucket REST API
curl -v -X GET 
-H 'Authorization: Basic ****' 
-H 'Content-Type: application/json' 
'https://api.bitbucket.org/2.0/repositories/?role=contributor'

while being authenticated with user Test, the reply will contain only one repo, your repo A. 
I'm looking for a way to get this one repo A with any of `node-bitbucket` APIs. 

Is it clearer now?

**Comment by MunifTanjim** [comment]
Are you sure you are using `v1.13.0`?

Can you share the console output when you run the script with `DEBUG=bitbucket` environment variable?

Here's my example codes:

```js
await bitbucket.repositories.listPublic({
  role: 'contributor'
})
```

Here's my output when I run it with `DEBUG=bitbucket` env variable set:

```sh
  bitbucket REQUEST: { timeout: 0,
  method: 'GET',
  url:
   'https://api.bitbucket.org/2.0/repositories?role=contributor',
  headers:
   { accept: 'application/json',
     'user-agent': 'NodeBitbucket/1.13.0',
     authorization: 'Basic *** },
  body: undefined } +0ms
```
As you can see, it's requesting the correct url with the `?role=contributor` param.

**Comment by yuliabaron** [comment]
My bad, had to remove dist, and not it behaves fine. Sorry for the misunderstanding and thank you for the help
