### ISSUE TITLE
{workspace} in routes.json needs to be {username}

### ISSUE THREAD

**Issue by folofse** [MunifTanjim/node-bitbucket#48]
Hi @MunifTanjim 

Thank you for all your great work!!

I found that {workspace} in routes.json needs to be replaced with {username} in the urls, in order to work properly.

**The methods effected are:**
- createDeploymentVariable
- deleteDeploymentVariable
- listDeploymentVariables
- updateDeploymentVariable

**Comment by MunifTanjim** [comment]
:sweat_smile: the specification file is so inconsistent.

Eventually all the urls with `{username}` will be converted to `{workspace}` because of the recent GDPR changes.

> I found that {workspace} in routes.json needs to be replaced with {username} in the urls, in order to work properly.

The urls come from the specification file. And they forgot to change the parameter names. So instead of changing the url, I fixed the parameter names.

**Comment by MunifTanjim** [comment]
Published `v1.17.1` :tada: 

But npm is experiencing issues. It might take a while before it is available.
